import { nebula } from './nebula'
import { starfield } from './starfield'
import { blackhole } from './blackhole'
import { hopf } from './hopf'
import { storm } from './storm'
import { frequency } from './frequency'
import { cliffordTorus } from './clifford-torus'
import { magneticDust } from './magnetic-dust'
import { fibonacciCrystal } from './fibonacci-crystal'
import { paperFleet } from './paper-fleet'
import { textWave } from './text-wave'
import { textScatter } from './text-scatter'
import { textDissolve } from './text-dissolve'
import { textVarsity } from './text-varsity'
import type { Effect } from '../../engine/types'

export const ALL_PRESETS: Effect[] = [frequency, hopf, nebula, starfield, blackhole, storm, cliffordTorus, magneticDust, fibonacciCrystal, paperFleet, textWave, textScatter, textDissolve, textVarsity]
